"""Type stubs for pyopticam_ext — OptiTrack Camera SDK Python bindings."""

from __future__ import annotations
from enum import Enum
from typing import Optional
import numpy as np

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class eVideoMode(Enum):
    """Camera video output mode."""
    SegmentMode: eVideoMode
    GrayscaleMode: eVideoMode
    ObjectMode: eVideoMode
    InterleavedGrayscaleMode: eVideoMode
    PrecisionMode: eVideoMode
    BitPackedPrecisionMode: eVideoMode
    MJPEGMode: eVideoMode
    VideoMode: eVideoMode
    SynchronizationTelemetry: eVideoMode
    UnknownMode: eVideoMode

class eImagerGain(Enum):
    """Imager gain level."""
    Gain_Level0: eImagerGain
    Gain_Level1: eImagerGain
    Gain_Level2: eImagerGain
    Gain_Level3: eImagerGain
    Gain_Level4: eImagerGain
    Gain_Level5: eImagerGain
    Gain_Level6: eImagerGain
    Gain_Level7: eImagerGain

class eCameraState(Enum):
    """Camera initialization state."""
    Uninitialized: eCameraState
    InitializingDevice: eCameraState
    InitializingCamera: eCameraState
    Initializing: eCameraState
    WaitingForChildDevices: eCameraState
    WaitingForDeviceInitialization: eCameraState
    Initialized: eCameraState
    Disconnected: eCameraState
    Shutdown: eCameraState

class eStatusLEDs(Enum):
    """Camera status LED selector."""
    GreenStatusLED: eStatusLEDs
    RedStatusLED: eStatusLEDs
    CaseStatusLED: eStatusLEDs
    IlluminationLED: eStatusLEDs

class eOptimization(Enum):
    ForceTimelyDelivery: eOptimization
    FavorTimelyDelivery: eOptimization
    ForceCompleteDelivery: eOptimization
    eOptimizationCount: eOptimization

class Modes(Enum):
    """FrameGroup synchronization mode."""
    none: Modes
    Software: Modes
    Hardware: Modes

# ---------------------------------------------------------------------------
# Simple data types
# ---------------------------------------------------------------------------

class sStatusLightColor:
    Red: int
    Green: int
    Blue: int

class cUID:
    def SetValue(self, high: int, low: int) -> None: ...
    def LowBits(self) -> int: ...
    def HighBits(self) -> int: ...
    def Valid(self) -> bool: ...
    @staticmethod
    def Generate() -> cUID: ...

# ---------------------------------------------------------------------------
# CameraEntry / lists
# ---------------------------------------------------------------------------

class CameraEntry:
    """Lightweight description of a camera as reported by CameraManager."""
    def UID(self) -> cUID: ...
    def Serial(self) -> int: ...
    def Revision(self) -> int: ...
    def Name(self) -> str: ...
    def State(self) -> eCameraState: ...
    def IsVirtual(self) -> bool: ...
    def SerialString(self) -> str: ...

class CameraList:
    """A snapshot list of connected cameras. Automatically populated on construction."""
    def __init__(self) -> None: ...
    def get(self, index: int) -> CameraEntry: ...
    def Count(self) -> int: ...
    def Refresh(self) -> None: ...

class HardwareKeyList:
    def __init__(self) -> None: ...
    def get(self, index: int) -> CameraEntry: ...
    def Count(self) -> int: ...

class HubList:
    def __init__(self) -> None: ...
    def get(self, index: int) -> CameraEntry: ...
    def Count(self) -> int: ...

class HardwareDeviceList:
    def __init__(self) -> None: ...
    def get(self, index: int) -> CameraEntry: ...
    def Count(self) -> int: ...

# ---------------------------------------------------------------------------
# Frame / FrameGroup
# ---------------------------------------------------------------------------

class Frame:
    def ObjectCount(self) -> int: ...
    def FrameID(self) -> int: ...
    def FrameType(self) -> int: ...
    def MJPEGQuality(self) -> int: ...
    def Object(self, index: int) -> object: ...
    def IsInvalid(self) -> bool: ...
    def IsEmpty(self) -> bool: ...
    def IsGrayscale(self) -> bool: ...
    def Width(self) -> int: ...
    def Height(self) -> int: ...
    def Left(self) -> int: ...
    def Top(self) -> int: ...
    def Right(self) -> int: ...
    def Bottom(self) -> int: ...
    def Scale(self) -> float: ...
    def TimeStamp(self) -> float: ...
    def IsSynchInfoValid(self) -> bool: ...
    def IsExternalLocked(self) -> bool: ...
    def IsRecording(self) -> bool: ...
    def HardwareTimeStampValue(self) -> int: ...
    def HardwareTimeStamp(self) -> float: ...
    def IsHardwareTimeStamp(self) -> bool: ...
    def HardwareTimeFreq(self) -> float: ...
    def MasterTimingDevice(self) -> bool: ...
    def ImageDataSize(self) -> int: ...
    def GrayscaleDataSize(self) -> int: ...
    def SetObjectCount(self, count: int) -> None: ...
    def RemoveObject(self, index: int) -> None: ...

class FrameGroup:
    def __init__(self) -> None: ...
    def Count(self) -> int: ...
    def GetFrame(self, index: int) -> Frame: ...
    def AddFrame(self, frame: Frame) -> None: ...
    def SetMode(self, mode: Modes) -> None: ...
    def Mode(self) -> Modes: ...
    def SetTimeStamp(self, ts: float) -> None: ...
    def SetTimeSpread(self, spread: float) -> None: ...
    def SetEarliestTimeStamp(self, ts: float) -> None: ...
    def SetLatestTimeStamp(self, ts: float) -> None: ...
    def TimeSpread(self) -> float: ...
    def TimeStamp(self) -> float: ...
    def EarliestTimeStamp(self) -> float: ...
    def LatestTimeStamp(self) -> float: ...
    def FrameID(self) -> int: ...
    def TimeSpreadDeviation(self) -> float: ...
    def DroppedFrames(self) -> int: ...

# ---------------------------------------------------------------------------
# Camera
# ---------------------------------------------------------------------------

class Camera:
    """Represents a connected OptiTrack camera."""
    def Width(self) -> int: ...
    def Height(self) -> int: ...
    def LatestFrame(self) -> Optional[Frame]: ...
    def NextFrame(self) -> Optional[Frame]: ...
    def Name(self) -> str: ...
    def Start(self) -> None: ...
    def Stop(self) -> None: ...
    def IsCameraRunning(self) -> bool: ...
    def SetNumeric(self, enable: bool, value: int) -> None: ...
    def SetExposure(self, exposure: int) -> None: ...
    def SetThreshold(self, threshold: int) -> None: ...
    def SetIntensity(self, intensity: int) -> None: ...
    def SetPrecisionCap(self, cap: int) -> None: ...
    def SetShutterDelay(self, delay: int) -> None: ...
    def SetStrobeOffset(self, offset: int) -> None: ...
    def SetFrameRate(self, rate: int) -> None: ...
    def FrameRate(self) -> int: ...
    def SetFrameDecimation(self, decimation: int) -> None: ...
    def FrameDecimation(self) -> int: ...
    def GrayscaleDecimation(self) -> int: ...
    def PrecisionCap(self) -> int: ...
    def ShutterDelay(self) -> int: ...
    def StrobeOffset(self) -> int: ...
    def Exposure(self) -> int: ...
    def Threshold(self) -> int: ...
    def Intensity(self) -> int: ...
    def SetVideoType(self, mode: eVideoMode) -> None: ...
    def IsVideoTypeSupported(self, mode: eVideoMode) -> bool: ...
    def IsVideoTypeSynchronous(self, mode: eVideoMode) -> bool: ...
    def DataRate(self) -> int: ...
    def PacketSize(self) -> int: ...
    def SetGrayscaleDecimation(self, decimation: int) -> None: ...
    def SendEmptyFrames(self, enable: bool) -> None: ...
    def SendInvalidFrames(self, enable: bool) -> None: ...
    def SetLateDecompression(self, enable: bool) -> None: ...
    def LateDecompression(self) -> bool: ...
    def Serial(self) -> int: ...
    def SerialString(self) -> str: ...
    def Model(self) -> int: ...
    def SubModel(self) -> int: ...
    def Revision(self) -> int: ...
    def HardwareInterface(self) -> int: ...
    def CameraID(self) -> int: ...
    def CameraIDValid(self) -> bool: ...
    def SetIRFilter(self, enable: bool) -> None: ...
    def IRFilter(self) -> bool: ...
    def IsFilterSwitchAvailable(self) -> bool: ...
    def SetAGC(self, enable: bool) -> None: ...
    def AGC(self) -> bool: ...
    def IsAGCAvailable(self) -> bool: ...
    def SetAEC(self, enable: bool) -> None: ...
    def AEC(self) -> bool: ...
    def IsAECAvailable(self) -> bool: ...
    def SetImagerGain(self, gain: eImagerGain) -> None: ...
    def ImagerGain(self) -> eImagerGain: ...
    def SetHighPowerMode(self, enable: bool) -> None: ...
    def HighPowerMode(self) -> bool: ...
    def ActualFrameRate(self) -> float: ...
    def SetMJPEGQuality(self, quality: int, force: bool) -> None: ...
    def MJPEGQuality(self) -> int: ...
    def SetContinuousIR(self, enable: bool) -> None: ...
    def ContinuousIR(self) -> bool: ...
    def SetRinglightEnabledWhileStopped(self, enable: bool) -> None: ...
    def RinglightEnabledWhileStopped(self) -> bool: ...
    def SetLED(self, led: eStatusLEDs, enable: bool) -> None: ...
    def SetAllLED(self, led: eStatusLEDs, enable: bool) -> None: ...
    def SetStatusIntensity(self, intensity: int) -> None: ...
    def StatusRingLightCount(self) -> int: ...
    def SetStatusRingLights(self, index: int, enable: bool) -> None: ...
    def SetStatusRingRGB(self, r: int, g: int, b: int) -> None: ...
    def SetTextOverlay(self, enable: bool) -> None: ...
    def TextOverlay(self) -> bool: ...
    def SetMarkerOverlay(self, enable: bool) -> None: ...
    def MarkerOverlay(self) -> bool: ...
    def IsInitialized(self) -> bool: ...
    def IsDisconnected(self) -> bool: ...
    def State(self) -> eCameraState: ...
    def UID(self) -> cUID: ...
    def IsCamera(self) -> bool: ...
    def IsUSB(self) -> bool: ...
    def IsEthernet(self) -> bool: ...
    def IsHub(self) -> bool: ...
    def SetCameraResolution(self, resolution_id: int) -> None: ...
    def MinimumExposureValue(self) -> int: ...
    def MaximumExposureValue(self) -> int: ...
    def MinimumFrameRateValue(self) -> int: ...
    def MaximumFrameRateValue(self) -> int: ...
    def MinimumThreshold(self) -> int: ...
    def MaximumThreshold(self) -> int: ...
    def Shutdown(self) -> None: ...
    def AttachModule(self, module: object) -> None: ...
    def RemoveModule(self, module: object) -> None: ...

# ---------------------------------------------------------------------------
# CameraManager
# ---------------------------------------------------------------------------

class CameraManagerListener:
    def CameraConnected(self) -> None: ...
    def CameraRemoved(self) -> None: ...
    def CameraInitialized(self) -> None: ...

class CameraManager:
    """Singleton managing all connected OptiTrack cameras. Access via CameraManager.X()."""
    @staticmethod
    def X() -> CameraManager: ...
    @staticmethod
    def Ptr() -> CameraManager: ...
    @staticmethod
    def IsActive() -> bool: ...
    @staticmethod
    def DestroyInstance() -> None: ...
    def WaitForInitialization(self) -> bool: ...
    def AreCamerasInitialized(self) -> bool: ...
    def AreCamerasShutdown(self) -> bool: ...
    def Shutdown(self) -> None: ...
    def GetCameraBySerial(self, serial: int) -> Optional[Camera]: ...
    def GetCamera(self, uid: Optional[cUID] = None) -> Optional[Camera]: ...
    def GetCameraList(self, list: CameraList) -> None: ...
    def GetHardwareKey(self) -> Optional[Camera]: ...
    def GetDevice(self, uid: cUID) -> Optional[Camera]: ...
    def ScanForCameras(self) -> None: ...
    def RegisterListener(self, listener: CameraManagerListener) -> None: ...
    def UnregisterListener(self) -> None: ...
    def AddCamera(self, camera: Camera) -> None: ...
    def RemoveCamera(self, camera: Camera) -> None: ...
    def SoftwareTrigger(self) -> None: ...
    def TimeStamp(self) -> float: ...
    @staticmethod
    def CameraFactory(revision: int, init: bool = True, serial: int = 0) -> Camera: ...

# ---------------------------------------------------------------------------
# cModuleSync
# ---------------------------------------------------------------------------

class cModuleSync:
    """Frame synchronizer that groups frames from multiple cameras."""
    @staticmethod
    def Create() -> cModuleSync: ...
    @staticmethod
    def Destroy(sync: cModuleSync) -> None: ...
    def AddCamera(self, camera: Camera) -> None: ...
    def RemoveAllCameras(self) -> None: ...
    def CameraCount(self) -> int: ...
    def GetFrameGroup(self) -> Optional[FrameGroup]: ...
    def LastFrameGroupMode(self) -> Modes: ...
    def AllowIncompleteGroups(self) -> bool: ...
    def SetAllowIncompleteGroups(self, allow: bool) -> None: ...
    def SetOptimization(self, opt: eOptimization) -> None: ...
    def Optimization(self) -> eOptimization: ...
    def SetSuppressOutOfOrder(self, suppress: bool) -> None: ...
    def FrameDeliveryRate(self) -> float: ...
    def PostFrame(self, frame: Frame) -> None: ...

# ---------------------------------------------------------------------------
# cCameraLibraryStartupSettings
# ---------------------------------------------------------------------------

class cCameraLibraryStartupSettings:
    def __init__(self) -> None: ...
    @staticmethod
    def X() -> cCameraLibraryStartupSettings: ...
    def EnableDevelopment(self) -> None: ...
    def IsDevelopmentEnabled(self) -> bool: ...

# ---------------------------------------------------------------------------
# Module-level functions
# ---------------------------------------------------------------------------

def GetCameraList(manager: CameraManager) -> CameraList:
    """Return a CameraList populated from the given CameraManager."""
    ...

def GetFrameGroup(sync: cModuleSync, timeout_ms: int = 100) -> Optional[FrameGroup]:
    """Block until a valid FrameGroup is available or timeout_ms elapses."""
    ...

def FillTensorFromFrameGroup(
    camera: Camera,
    frame_group: FrameGroup,
    array: np.ndarray,
) -> None:
    """Copy grayscale frame data from frame_group into the pre-allocated numpy array."""
    ...

def GetFrameGroupObjectArray(sync: cModuleSync) -> np.ndarray:
    """Return an (8, 255, 3) float32 array of tracked object positions (x, y, radius)."""
    ...

def GetFrameArrayNoSync(cameras: list) -> np.ndarray:
    """Return a (N, H, W) uint8 array of grayscale frames fetched individually per camera, without a sync module."""
    ...

def GetSlowFrameArray(serials: np.ndarray) -> np.ndarray:
    """Return a (N, H, W) uint8 array of grayscale frames fetched individually per camera."""
    ...
